from pathlib import Path
import re
p=Path(__file__).resolve().parents[1]/"index.html";s=p.read_text(encoding="utf-8")
a=s.index("function renderDarkPoolSection()");b=s.index("\n        function ",a+10)
fn=r'''function renderDarkPoolSection(){
 const t=macroDatabase.__darkPoolPrints||{assets:{},prints:[]},assets=t.assets||{},keys=Object.keys(assets),selected=(window.__darkPoolTicker&&assets[window.__darkPoolTicker])?window.__darkPoolTicker:(keys[0]||"SPY");window.__darkPoolTicker=selected;
 const a=assets[selected]||{ticker:selected,lastPrice:null,priceSeries:[],prints:[],venueClusters:[],dailyOffExchange:{}},ps=a.priceSeries||[],W=1120,H=430,L=72,R=30,T=28,B=62,lo=ps.length?Math.min(...ps.map(x=>+x.price)):0,hi=ps.length?Math.max(...ps.map(x=>+x.price)):1,pad=(hi-lo||1)*.12,y0=lo-pad,y1=hi+pad,minTs=ps.length?Math.min(...ps.map(x=>+x.ts)):0,maxTs=ps.length?Math.max(...ps.map(x=>+x.ts)):1,span=Math.max(maxTs-minTs,1),px=ts=>L+(ts-minTs)*(W-L-R)/span,py=v=>T+(y1-v)*(H-T-B)/Math.max(y1-y0,1);
 const n=v=>Number.isFinite(Number(v))?Number(v).toLocaleString("es-ES",{maximumFractionDigits:2}):"—",money=v=>Number.isFinite(Number(v))?fmtCompactMoney(v):"—";
 const grid=[0,.25,.5,.75,1].map(q=>{let y=T+q*(H-T-B),v=y1-q*(y1-y0);return '<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y+'" y2="'+y+'" stroke="#334155" stroke-dasharray="3 5"/><text x="'+(L-10)+'" y="'+(y+4)+'" text-anchor="end" fill="#dbe4f0" font-size="11">'+n(v)+'</text>'}).join("");
 const ticks=[0,.2,.4,.6,.8,1].map(q=>{let ts=minTs+q*span;return '<line x1="'+px(ts)+'" x2="'+px(ts)+'" y1="'+T+'" y2="'+(H-B)+'" stroke="#1e293b" stroke-dasharray="2 6"/><text x="'+px(ts)+'" y="'+(H-27)+'" text-anchor="middle" fill="#dbe4f0" font-size="10">'+esc(new Date(ts).toLocaleDateString("es-ES",{day:"2-digit",month:"2-digit"}))+'</text>'}).join("");
 const xy=ps.map(p=>px(+p.ts).toFixed(1)+","+py(+p.price).toFixed(1)).join(" "),path=ps.length?'<polyline points="'+xy+'" fill="none" stroke="#60a5fa" stroke-width="2.8" stroke-linejoin="round"/>':"";
 const dots=(a.prints||[]).slice(0,120).map(p=>{const price=Number.isFinite(+p.price)?+p.price:+p.priceApprox,ts=Number.isFinite(+p.approxTs)?+p.approxTs:minTs;const x=px(Math.max(minTs,Math.min(maxTs,ts))),y=Number.isFinite(price)?py(price):(H-B);const buy=p.side==="BUY",sell=p.side==="SELL",c=buy?"#34d399":sell?"#f87171":"#facc15",r=Math.max(4,Math.min(15,Math.sqrt(Math.max(+p.size||1,1))/10));return '<circle cx="'+x.toFixed(1)+'" cy="'+Math.max(T,Math.min(H-B,y)).toFixed(1)+'" r="'+r.toFixed(1)+'" fill="'+c+'" fill-opacity=".88" stroke="#fff" stroke-opacity=".5"><title>'+esc(p.timestamp||"")+' · '+(buy?"BUY":sell?"SELL":"PRINT")+' · '+n(p.size)+' sh · '+money(p.notional||price*(p.size||0))+'</title></circle>'}).join("");
 const dpx=a.dailyOffExchange||{},rows=(a.prints||[]).slice(0,100).map(p=>'<tr class="border-b border-gray-800"><td class="py-2 px-2 text-xs">'+esc(p.timestamp||"—")+'</td><td class="py-2 px-2 text-xs '+(p.side==="BUY"?"text-emerald-300":p.side==="SELL"?"text-red-300":"text-yellow-300")+'">'+(p.side||"PRINT")+'</td><td class="py-2 px-2 text-right text-xs">'+n(p.size)+'</td><td class="py-2 px-2 text-right text-xs">'+money(p.notional||p.priceApprox*(p.size||0))+'</td><td class="py-2 px-2 text-xs">'+esc(p.venue||"TRF")+'</td></tr>').join("");
 const vc=(a.venueClusters||[]).map(v=>'<div class="grid grid-cols-[90px_1fr_100px] gap-2 items-center text-xs"><b class="text-white">'+esc(v.venue)+'</b><div class="h-2 bg-gray-900 rounded"><div class="h-2 bg-blue-400 rounded" style="width:'+Math.min(100,(+v.shares||0)/Math.max(+a.shareCount||1,1)*100)+'%"></div></div><span class="text-right text-gray-300">'+n(v.shares)+'</span></div>').join("");
 const sel=keys.map(k=>'<option value="'+esc(k)+'" '+(k===selected?"selected":"")+'>'+esc(k)+" · "+esc(instrumentName(k))+'</option>').join("");
 const svg=ps.length?'<svg viewBox="0 0 '+W+' '+H+'" class="w-full min-w-[760px] h-[430px]">'+grid+ticks+path+dots+'</svg>':'<div class="h-[430px] grid place-items-center text-gray-500">Sin serie intradía.</div>';
 return '<section id="sec-darkpool" class="space-y-4"><div class="glass rounded-2xl p-5"><div class="flex justify-between items-center gap-3"><div><div class="text-[10px] uppercase tracking-wider text-gray-500">INSTITUTIONAL FLOW DESK</div><h2 class="text-xl font-black text-white mt-1">DARK POOLS · '+instrumentName(selected)+' · '+esc(selected)+'</h2><p class="text-sm text-gray-300 mt-1">Mapa de precio + prints. Puntos = operaciones visibles; tamaño = acciones aproximadas. Los datos modelizados/proxy permanecen identificados.</p></div><select onchange="window.__darkPoolTicker=this.value;renderContent()" class="bg-gray-900 border border-gray-600 text-white rounded-lg px-3 py-2">'+sel+'</select></div><div class="grid grid-cols-2 md:grid-cols-5 gap-3 mt-4">'+[['PRECIO',fmtNum(a.lastPrice,2)],['PRINTS',n(a.printCount||0)],['SHARES',n(a.shareCount||0)],['NOTIONAL',money(a.notional)],['OFF-EXCHANGE',Number.isFinite(+dpx.offExchangePct)?(+dpx.offExchangePct).toFixed(1)+"%":"—"]].map(x=>'<div class="metric p-3"><span class="text-[9px] text-gray-500">'+x[0]+'</span><b class="block text-lg text-white mt-1">'+x[1]+'</b></div>').join("")+'</div></div><div class="metric rounded-xl p-5"><div class="flex justify-between"><div><b class="text-sm text-white">PRECIO · PRINTS · EJES TEMPORALES</b><div class="text-[10px] text-gray-500 mt-1">Eje Y = precio · eje X = fecha/hora. Hover sobre cada punto = detalle del print.</div></div><div class="flex gap-3 text-[10px]"><span class="text-emerald-300">● BUY</span><span class="text-red-300">● SELL</span><span class="text-yellow-300">● PRINT</span></div></div><div class="overflow-x-auto mt-3">'+svg+'</div></div><div class="grid grid-cols-1 xl:grid-cols-[1.4fr_1fr] gap-4"><div class="metric rounded-xl p-4 overflow-x-auto"><b class="text-sm text-white">PRINTS VISIBLES · ÚLTIMOS 100</b><table class="w-full min-w-[700px] mt-3"><thead><tr class="border-b border-gray-700 text-[10px] text-gray-400 uppercase"><th class="text-left py-2 px-2">Hora</th><th class="text-left py-2 px-2">Lado</th><th class="text-right py-2 px-2">Acciones</th><th class="text-right py-2 px-2">Notional</th><th class="text-left py-2 px-2">Venue</th></tr></thead><tbody>'+rows+'</tbody></table></div><div class="metric rounded-xl p-4"><b class="text-sm text-white">CONCENTRACIÓN POR VENUE</b><p class="text-[10px] text-gray-500 mt-1">Agrupación reportada; no implica identidad de un fondo.</p><div class="space-y-3 mt-4">'+(vc||'<div class="text-xs text-gray-500">Sin clusters publicados.</div>')+'</div><div class="mt-5 text-xs text-gray-400"><b class="text-white">Off-exchange:</b> '+(Number.isFinite(+dpx.offExchangePct)?(+dpx.offExchangePct).toFixed(1)+"% del volumen":"—")+'. Un print fuera de bolsa no demuestra por sí solo acumulación institucional.</div></div></div></section>';
}'''
s=s[:a]+fn+s[b:]
p.write_text(s,encoding="utf-8")
print("DARK POOL UI PHASE OK")
