from pathlib import Path
p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_text(encoding='utf-8')
# Clear labels and remove the confusing N/D presentation.
s=s.replace("EXPECTED MOVE · MODEL</span><b class="block text-lg text-white">'+(Number.isFinite(Number(p.expectedMove))?'±'+fmtNum(p.expectedMove,2):'N/D')+'</b>",
"EXPECTED MOVE · IV → RANGE</span><b class="block text-lg text-white">'+(Number.isFinite(Number(p.expectedMove))?'±'+fmtNum(p.expectedMove,2):'—')+'</b><span class="text-[9px] text-gray-500">'+(Number.isFinite(Number(p.expectedMove))?fmtPct(p.expectedMovePct,2)+' · según IV y vencimiento':'IV/vencimiento no disponible')+'</span>")
s=s.replace("ATM IV · OBSERVED</span><b class="block text-lg text-white">'+fmtPct(p.ivAtm)+'</b>",
"ATM IV · VOLATILIDAD IMPLÍCITA</span><b class="block text-lg text-white">'+fmtPct(p.ivAtm)+'</b><span class="text-[9px] text-gray-500">IV ATM de la cadena pública</span>")
needle='<div class="metric rounded-xl p-4"><b class="text-sm text-white">Cómo leerlo</b>'
advanced='''<div class="metric rounded-xl p-5"><div class="flex flex-wrap justify-between gap-3"><div><b class="text-sm text-white">OPCIONES · MÉTRICAS PROFESIONALES</b><p class="text-[10px] text-gray-500 mt-1">OI, volatilidad y concentración por strike. No mezclar GEX entre venues.</p></div><div class="mini-pill">'+esc(m.source||'')+'</div></div><div class="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3 mt-4">'+[['CALL WALL',fmtNum(p.callWall??m.topCallStrike,2)],['CALL OI',fmtNum(p.callWallOi,0)],['PUT WALL',fmtNum(p.putWall??m.topPutStrike,2)],['PUT OI',fmtNum(p.putWallOi,0)],['25D SKEW',Number.isFinite(Number(p.skew25d))?fmtNum(p.skew25d,2)+' vol pts':'—'],['OI > SPOT',Number.isFinite(Number(p.oiAbovePct))?fmtNum(p.oiAbovePct,1)+'%':'—'],['OI < SPOT',Number.isFinite(Number(p.oiBelowPct))?fmtNum(p.oiBelowPct,1)+'%':'—'],['GAMMA REGIME',Number(p.gammaNet)<0?'NEGATIVO':'POSITIVO']].map(x=>'<div class="p-3 rounded-lg bg-gray-900"><span class="text-[9px] text-gray-500">'+x[0]+'</span><b class="block text-sm text-white mt-1">'+x[1]+'</b></div>').join('')+'</div><div class="mt-4 grid grid-cols-1 xl:grid-cols-2 gap-4"><div><div class="text-[10px] text-gray-400 mb-2">CONCENTRACIÓN OI POR STRIKE · TOP CLUSTERS</div>'+((p.strikeLevels||p.topOiStrikes||[]).slice(0,10).map(x=>'<div class="flex justify-between text-xs border-b border-gray-800 py-2"><span>'+fmtNum(x.strike,2)+'</span><span>OI '+fmtNum(x.totalOi??((x.callOi||0)+(x.putOi||0)),0)+'</span><span>GEX '+fmtCompactMoney(x.gex)+'</span></div>').join('')||'<div class="text-xs text-gray-500">Sin desglose de OI por strike.</div>')+'</div><div><div class="text-[10px] text-gray-400 mb-2">LECTURA DEL GAMMA</div><p class="text-xs text-gray-300">GEX negativo implica que, bajo este modelo, el hedging estimado puede amplificar movimientos y favorecer un rango más reactivo. GEX positivo implica potencial amortiguación. Es una propiedad del modelo agregado, no una garantía de volatilidad futura ni una observación directa del dealer book.</p><div class="mt-3 text-xs text-gray-400">Call Wall: strike con mayor OI de calls. Put Wall: strike con mayor OI de puts. La cantidad de OI se muestra junto al nivel.</div></div></div></div>'''
if needle in s and "OPCIONES · MÉTRICAS PROFESIONALES" not in s:s=s.replace(needle,advanced+needle,1)
# Add order-flow rendering once.
if "function renderOrderFlowSection()" not in s:
 fn='''function renderOrderFlowSection(){const o=macroDatabase.__orderFlow||{markets:[]},ms=o.markets||[],n=v=>Number.isFinite(Number(v))?Number(v).toLocaleString("es-ES",{maximumFractionDigits:2}):"—";const cards=ms.map(m=>{const b=(m.bids||[]).slice(0,10),a=(m.asks||[]).slice(0,10),mx=Math.max(1,...b.map(x=>+x.size||0),...a.map(x=>+x.size||0)),side=(z,c)=>z.map(x=>'<div class="grid grid-cols-[82px_1fr_80px] gap-2 items-center text-[10px]"><span>'+n(x.price)+'</span><div class="h-2 bg-gray-900 rounded"><div class="h-2 '+c+'" style="width:'+Math.max(2,(+x.size||0)/mx*100)+'%"></div></div><span class="text-right">'+n(x.size)+'</span></div>').join("");return '<div class="metric rounded-xl p-4"><div class="flex justify-between"><b class="text-sm text-white">'+esc(m.display||m.symbol)+'</b><span class="mini-pill">Spread '+n(m.spread)+'</span></div><div class="text-[10px] text-gray-400 mt-1">'+esc(m.dataStatus||"")+'</div><div class="grid grid-cols-2 gap-4 mt-4"><div><div class="text-[10px] text-emerald-300 mb-2">BIDS</div>'+side(b,"bg-emerald-400")+'</div><div><div class="text-[10px] text-red-300 mb-2">ASKS</div>'+side(a,"bg-red-400")+'</div></div><div class="grid grid-cols-4 gap-2 mt-4 text-[10px]"><div>Bid<br><b>'+n(m.bestBid)+'</b></div><div>Ask<br><b>'+n(m.bestAsk)+'</b></div><div>Bid depth<br><b class="text-emerald-300">'+n(m.bidDepth??m.bidSize)+'</b></div><div>Ask depth<br><b class="text-red-300">'+n(m.askDepth??m.askSize)+'</b></div></div><div class="mt-3 text-[10px] text-gray-400">Imbalance <b class="'+(Number(m.imbalance)>=0?"text-emerald-300":"text-red-300")+'">'+n(m.imbalance)+'%</b> · '+esc(m.source||"")+'</div></div>"}).join("");return '<section id="sec-orderflow" class="space-y-4"><div class="glass rounded-2xl p-5"><div class="text-[10px] uppercase tracking-wider text-gray-400">MICROESTRUCTURA</div><h2 class="text-xl font-black text-white mt-1">ORDER FLOW · MARKET DEPTH</h2><p class="text-sm text-gray-300 mt-1">BTC/ETH: profundidad pública Deribit. Acciones/ETF: top-of-book; no se presenta como Level 2.</p></div><div class="grid grid-cols-1 xl:grid-cols-2 gap-4">'+(cards||'<div class="metric p-5 text-gray-400">Sin profundidad pública disponible.</div>')+'</div></section>';}'''
 s=s.replace("function renderGlobalView()",fn+"\n\n        function renderGlobalView()",1)
if "if(feed.orderFlow) macroDatabase.__orderFlow" not in s:s=s.replace("if(feed.squawkFlow) macroDatabase.__squawkFlow = feed.squawkFlow;","if(feed.squawkFlow) macroDatabase.__squawkFlow = feed.squawkFlow;\n                    if(feed.orderFlow) macroDatabase.__orderFlow = feed.orderFlow;",1)
if "macroDatabase.__orderFlow = macroDatabase.__orderFlow ||" not in s:s=s.replace("macroDatabase.__squawkFlow = macroDatabase.__squawkFlow || {};","macroDatabase.__squawkFlow = macroDatabase.__squawkFlow || {};\n        macroDatabase.__orderFlow = macroDatabase.__orderFlow || {updated:'—',markets:[]};",1)
if "$"+"{renderOrderFlowSection()}" not in s:s=s.replace("$"+"{renderCotSection()}$"+"{renderOptionsSection()}","$"+"{renderCotSection()}$"+"{renderOrderFlowSection()}$"+"{renderOptionsSection()}",1)
p.write_text(s,encoding='utf-8')
print('OPTIONS UI + ORDER FLOW UI PHASE OK')
